### ISSUE TITLE
Invalid name error

### ISSUE THREAD

**Issue by lorefnon** [vadymmarkov/Rexy#10]
When attempting to install 0.6.1 I receive the following error: 

```
Error: swift-package: error: the module at Tests/Rexy has an invalid name ('Rexy'): the name of a test module has no ‘Tests’ suffix
fix: rename the module at ‘Tests/Rexy’ to have a ‘Tests’ suffix
```

```
$ swift --version
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```

**Comment by justMaku** [comment]
Just run into this issue too, seems like this has been already fixed on `master` but hasn't been released as a new version yet.

I forked the project and released a new version (you could just push a tag) as a workaround.

**Comment by vadymmarkov** [comment]
@lorefnon @justMaku I've released a new version 😉 https://github.com/vadymmarkov/Rexy/releases/tag/0.7.0

**Comment by justMaku** [comment]
Oh, that's strange, for some reason Swift Package Manager wasn't picking up that version.
